### ISSUE TITLE
actionで動作させるとエラーになる

### ISSUE THREAD

**Issue by LAC-Ikeda** [covid19-kitakyushu/covid19-data-updater#14]
csvデータの取得に失敗して、data.jsonとinspections_summary.jsonが生成できないためコピーに失敗し自動更新が毎度こけている模様
ローカルでは正しく動作するうえ、以前はaction上でも成功していることがあったため理由は不明だが、action上でcsvが正しく生成できるようにする

**Comment by YasuhiroIhara** [comment]
5日以上スクリプトを更新してないので、原因不明ですね。私が経験したローカルでjsが動作しない
問題と同じかも知れません。今PRを出しているので、マージしてみてもらえませんか?

**Comment by LAC-Ikeda** [comment]
マージしました
13時の更新で様子を見てみます

**Comment by YasuhiroIhara** [comment]
8行目の変更にしないと、私のnodejsのバージョンだとエラーになっていました。その他の変更は、陽性者の状況カードのデータ作成と、Warning対応だけなので、既存のデータ作成には影響しません

**Comment by LAC-Ikeda** [comment]
ネットワーク関連のエラーが出ているようです。
13時の更新は3回失敗しました。

以下エラーログの一部
getaddrinfo EAI_AGAIN

**Comment by YasuhiroIhara** [comment]
Actionsの実行環境で、DNSが引けなくなっているなっているんですかね。手動でActionsを実行すると成功したのですか?

**Comment by LAC-Ikeda** [comment]
はい、手動で再実行しました。
いつもは1度再実行をかければ成功するのですが、先ほどは3度再実行かけてようやく成功しました。

**Comment by YasuhiroIhara** [comment]
手動で実行するとできるのも環境依存っぽいですね。

**Comment by YasuhiroIhara** [comment]
もしかして、全世界公開を止めて、日本だけにしたのが問題? また、全世界公開に戻してみます。
19時の状況を見ましょう

**Comment by LAC-Ikeda** [comment]
今までもエラーは出ていたので、それは問題ないと思います。
通信ができるようになる前にnode main.jsが動いているのが問題かと思っています。
node main.jsの前にsleepを入れてみる形で19時の分を試してみます。

**Comment by YasuhiroIhara** [comment]
今回は自動で成功したようですね

**Comment by LAC-Ikeda** [comment]
はい、無事動きました。
ちょっと雑ですが、問題が出るまでとりあえずこれで対応完了とします。
